((nil . ((eval . (set (make-local-variable 'my-project-path)
                      (file-name-directory
                       (let ((d (dir-locals-find-file default-directory)))
                         (if (stringp d) d (car d))))))))
 (c++-mode . (
              (flycheck-checker . c/c++-gcc)
              (flycheck-c/c++-gcc-executable . "avr-gcc")
              (eval . (setq flycheck-gcc-include-path
                          (list (expand-file-name "core/MegaCore/avr/variants/64-pin-avr" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/cores/MCUdude_corefiles" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/libraries/EEPROM/src" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/libraries/SPI/src" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/libraries/SoftwareSerial/src" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/libraries/Timer/src" (projectile-project-root))
                                (expand-file-name "core/MegaCore/avr/libraries/Wire/src" (projectile-project-root))
                                (expand-file-name "lib/Button" (projectile-project-root))
                                (expand-file-name "lib/CDS" (projectile-project-root))
                                (expand-file-name "lib/DHT" (projectile-project-root))
                                (expand-file-name "lib/HT16K33" (projectile-project-root))
                                (expand-file-name "lib/KappaDateTime" (projectile-project-root))
                                (expand-file-name "lib/KappaGPS" (projectile-project-root))
                                (expand-file-name "lib/KappaSegment" (projectile-project-root))
                                (expand-file-name "lib/NoInteraction" (projectile-project-root))
                                (expand-file-name "lib/Rtc" (projectile-project-root))
                                (expand-file-name "lib/VariableTimedAction/src" (projectile-project-root)))
                          ))
              )))
